Exploring NUMPY Package

MY FIRST DAY FDP

In [ ]:
import numpy as np

In [ ]:
ZeroD=np.array(46)
print(type(ZeroD))

<class 'numpy.ndarray'>


In [ ]:
OneD=np.array([12,45,89,47,45,78,89])
OneD

array([12, 45, 89, 47, 45, 78, 89])

In [ ]:
TwoD=np.array([[12,12,25,45],[78,18,91,46],[4,8,9,4],[1,2,3,4]])
TwoD

array([[12, 12, 25, 45],
       [78, 18, 91, 46],
       [ 4,  8,  9,  4],
       [ 1,  2,  3,  4]])

In [ ]:
ThreeD=np.array([[[1,8,4,6],[2,8,9,7],[4,6,8,3]]])
ThreeD

array([[[1, 8, 4, 6],
        [2, 8, 9, 7],
        [4, 6, 8, 3]]])

In [ ]:
np.ndim(TwoD)

2

In [ ]:
np.size(TwoD)

16

In [ ]:
np.shape(TwoD)

(4, 4)

In [ ]:
print(type(ThreeD))

<class 'numpy.ndarray'>


In [ ]:
print(len(OneD))

7


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10,30,8)

array([10, 18, 26])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(1,25,15)
np.linspace(4,50,7)

array([ 4.        , 11.66666667, 19.33333333, 27.        , 34.66666667,
       42.33333333, 50.        ])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(4)

array([0.88827388, 0.43204357, 0.59760333, 0.23340719])

In [ ]:
np.random.rand(4,2,5)

array([[[0.99280521, 0.21037566, 0.25698709, 0.97449548, 0.46737239],
        [0.94492468, 0.49930968, 0.09935237, 0.40941626, 0.30640473]],

       [[0.45404963, 0.91045937, 0.12582527, 0.27555518, 0.54424998],
        [0.07687151, 0.98185106, 0.63450085, 0.92443963, 0.38422524]],

       [[0.31876182, 0.41131729, 0.84677766, 0.21608677, 0.6468597 ],
        [0.61050559, 0.42944521, 0.08951347, 0.63114323, 0.29373844]],

       [[0.05433635, 0.12779893, 0.96559207, 0.21228953, 0.59727701],
        [0.21521125, 0.40958437, 0.33079515, 0.91138039, 0.56748055]]])

In [ ]:
np.random.randn(2)

array([-2.56582852, -3.05857413])

In [ ]:
np.random.randn(3,2)

array([[-0.34125138,  0.06868752],
       [-1.02180527,  1.60903212],
       [-1.44603534, -0.65276882]])

In [ ]:
np.random.randint(1,6)

3

In [ ]:
np.random.randint(1,6,10)

array([3, 4, 3, 5, 1, 3, 4, 4, 4, 5])

In [ ]:
b=np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
b.shape

(15,)

In [ ]:
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [ ]:
np.min(b)

np.int64(1)

In [ ]:
np.max(b)

np.int64(29)

In [ ]:
print(b.min())

1


In [ ]:
print(b.max())

29


In [ ]:
b.argmax()

np.int64(14)

In [ ]:
b[1:14]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [ ]:
b[:5]

array([1, 3, 5, 7, 9])

In [ ]:
b[3:]

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])